adding jwt authentication, user model
oriarb/web-applications pull request #4
Opened 2024-12-11 17:19 UTC by oriarb

2024-12-22 09:15 UTC, orcohen2107 requested changes

2024-12-22 09:15 UTC, orcohen2107 commented on requests/requests.auth.rest
> +  "password": "123456",
not need confirmPassword?

2024-12-22 09:15 UTC, orcohen2107 commented on src/common/auth-middleware.ts
> +    const decoded = verify(token, secret);
type

2024-12-22 09:15 UTC, orcohen2107 commented on src/controllers/auth.ts
> +    res.json({ error: 'Please fill all fields' });
use joi instead is better

2024-12-22 09:15 UTC, orcohen2107 commented on src/controllers/auth.ts
> +    const salt = await genSalt(10);
types

2024-12-22 09:15 UTC, orcohen2107 commented on src/controllers/auth.ts
> +    const user = await User.findOne({ email });
what about check username?
it also need to be uniqe

2024-12-22 09:15 UTC, orcohen2107 commented on src/controllers/auth.ts
> +    const isMatch = await compare(password, user.password);
its return user.password without the salt? 
because in the register you enter with salt

2024-12-22 09:15 UTC, orcohen2107 commented on src/controllers/auth.ts
> +
you have duplicate code here and the middlewere and th logout.

2024-12-22 09:15 UTC, orcohen2107 commented on src/models/user.model.ts
> +  tokens: {
why we save the token in db?

2024-12-22 17:51 UTC, oriarb commented on src/controllers/auth.ts
> +    res.json({ error: 'Please fill all fields' });
what is joi?

2024-12-30 21:54 UTC, orcohen2107 commented on src/controllers/auth.ts
> +    const user = await User.findOne({ email });
?

2025-01-02 07:42 UTC, orcohen2107 approved these changes

2025-01-02 12:28 UTC, merged